// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Test
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Bar15 : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Bar15"",""namespace"":""Test"",""fields"":[{""name"":""Bar16"",""type"":""long""},{""name"":""Bar17"",""type"":[""null"",""int""]},{""name"":""Bar18"",""type"":[""null"",""int""]},{""name"":""Bar19"",""type"":[""null"",""int""]},{""name"":""Bar20"",""type"":[""null"",""int""]},{""name"":""Bar21"",""type"":""int""},{""name"":""Bar22"",""type"":""int""},{""name"":""Bar23"",""type"":{""type"":""int"",""logicalType"":""date""}},{""name"":""Bar24"",""type"":{""type"":""string"",""logicalType"":""uuid""}}]}");
		private long _Bar16;
		private System.Nullable<System.Int32> _Bar17;
		private System.Nullable<System.Int32> _Bar18;
		private System.Nullable<System.Int32> _Bar19;
		private System.Nullable<System.Int32> _Bar20;
		private int _Bar21;
		private int _Bar22;
		private System.DateTime _Bar23;
		private System.Guid _Bar24;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Bar15._SCHEMA;
			}
		}
		public long Bar16
		{
			get
			{
				return this._Bar16;
			}
			set
			{
				this._Bar16 = value;
			}
		}
		public System.Nullable<System.Int32> Bar17
		{
			get
			{
				return this._Bar17;
			}
			set
			{
				this._Bar17 = value;
			}
		}
		public System.Nullable<System.Int32> Bar18
		{
			get
			{
				return this._Bar18;
			}
			set
			{
				this._Bar18 = value;
			}
		}
		public System.Nullable<System.Int32> Bar19
		{
			get
			{
				return this._Bar19;
			}
			set
			{
				this._Bar19 = value;
			}
		}
		public System.Nullable<System.Int32> Bar20
		{
			get
			{
				return this._Bar20;
			}
			set
			{
				this._Bar20 = value;
			}
		}
		public int Bar21
		{
			get
			{
				return this._Bar21;
			}
			set
			{
				this._Bar21 = value;
			}
		}
		public int Bar22
		{
			get
			{
				return this._Bar22;
			}
			set
			{
				this._Bar22 = value;
			}
		}
		public System.DateTime Bar23
		{
			get
			{
				return this._Bar23;
			}
			set
			{
				this._Bar23 = value;
			}
		}
		public System.Guid Bar24
		{
			get
			{
				return this._Bar24;
			}
			set
			{
				this._Bar24 = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Bar16;
			case 1: return this.Bar17;
			case 2: return this.Bar18;
			case 3: return this.Bar19;
			case 4: return this.Bar20;
			case 5: return this.Bar21;
			case 6: return this.Bar22;
			case 7: return this.Bar23;
			case 8: return this.Bar24;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Bar16 = (System.Int64)fieldValue; break;
			case 1: this.Bar17 = (System.Nullable<System.Int32>)fieldValue; break;
			case 2: this.Bar18 = (System.Nullable<System.Int32>)fieldValue; break;
			case 3: this.Bar19 = (System.Nullable<System.Int32>)fieldValue; break;
			case 4: this.Bar20 = (System.Nullable<System.Int32>)fieldValue; break;
			case 5: this.Bar21 = (System.Int32)fieldValue; break;
			case 6: this.Bar22 = (System.Int32)fieldValue; break;
			case 7: this.Bar23 = (System.DateTime)fieldValue; break;
			case 8: this.Bar24 = (System.Guid)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
