// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Test
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
    public partial class Foo : global::Avro.Specific.ISpecificRecord
    {
        public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Foo\",\"namespace\":\"Test\",\"fields\":[{\"name\":\"Bar\",\"type\":\"" +
                "string\"},{\"name\":\"Baz\",\"type\":[\"null\",\"int\"]}]}");
        private string _Bar;
        private System.Nullable<System.Int32> _Baz;
        public virtual global::Avro.Schema Schema
        {
            get
            {
                return Foo._SCHEMA;
            }
        }
        public string Bar
        {
            get
            {
                return this._Bar;
            }
            set
            {
                this._Bar = value;
            }
        }
        public System.Nullable<System.Int32> Baz
        {
            get
            {
                return this._Baz;
            }
            set
            {
                this._Baz = value;
            }
        }
        public virtual object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return this.Bar;
                case 1: return this.Baz;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0: this.Bar = (System.String)fieldValue; break;
                case 1: this.Baz = (System.Nullable<System.Int32>)fieldValue; break;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}
