// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Test
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Bar5 : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Bar5"",""namespace"":""Test"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""Bar6"",""type"":{""type"":""enum"",""name"":""Bar6"",""namespace"":""Test"",""symbols"":[""Value1"",""Value2"",""Value3"",""Value4"",""Value5"",""Value6"",""Value7"",""Value8""],""default"":""Value8""}},{""name"":""Bar7"",""type"":[""null"",""string""]},{""name"":""Bar8"",""type"":[""null"",""string""]},{""name"":""Bar9"",""type"":{""type"":""int"",""logicalType"":""date""}},{""name"":""Bar10"",""type"":[""null"",{""type"":""bytes"",""logicalType"":""decimal"",""precision"":22,""scale"":4}]},{""name"":""Bar11"",""type"":[""null"",{""type"":""bytes"",""logicalType"":""decimal"",""precision"":14,""scale"":2}]},{""name"":""Bar12"",""type"":[""null"",{""type"":""bytes"",""logicalType"":""decimal"",""precision"":19,""scale"":7}]},{""name"":""Bar13"",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":14,""scale"":2}},{""name"":""Bar14"",""type"":[""null"",""int""]},{""name"":""Bar15"",""type"":[""null"",{""type"":""record"",""name"":""Bar15"",""namespace"":""Test"",""fields"":[{""name"":""Bar16"",""type"":""long""},{""name"":""Bar17"",""type"":[""null"",""int""]},{""name"":""Bar18"",""type"":[""null"",""int""]},{""name"":""Bar19"",""type"":[""null"",""int""]},{""name"":""Bar20"",""type"":[""null"",""int""]},{""name"":""Bar21"",""type"":""int""},{""name"":""Bar22"",""type"":""int""},{""name"":""Bar23"",""type"":{""type"":""int"",""logicalType"":""date""}},{""name"":""Bar24"",""type"":{""type"":""string"",""logicalType"":""uuid""}}]}]}]}");
		private string _Id;
		private Test.Bar6 _Bar6 = Test.Bar6.Value8;
		private string _Bar7;
		private string _Bar8;
		private System.DateTime _Bar9;
		private System.Nullable<Avro.AvroDecimal> _Bar10;
		private System.Nullable<Avro.AvroDecimal> _Bar11;
		private System.Nullable<Avro.AvroDecimal> _Bar12;
		private Avro.AvroDecimal _Bar13;
		private System.Nullable<System.Int32> _Bar14;
		private Test.Bar15 _Bar15;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Bar5._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public Test.Bar6 Bar6
		{
			get
			{
				return this._Bar6;
			}
			set
			{
				this._Bar6 = value;
			}
		}
		public string Bar7
		{
			get
			{
				return this._Bar7;
			}
			set
			{
				this._Bar7 = value;
			}
		}
		public string Bar8
		{
			get
			{
				return this._Bar8;
			}
			set
			{
				this._Bar8 = value;
			}
		}
		public System.DateTime Bar9
		{
			get
			{
				return this._Bar9;
			}
			set
			{
				this._Bar9 = value;
			}
		}
		public System.Nullable<Avro.AvroDecimal> Bar10
		{
			get
			{
				return this._Bar10;
			}
			set
			{
				this._Bar10 = value;
			}
		}
		public System.Nullable<Avro.AvroDecimal> Bar11
		{
			get
			{
				return this._Bar11;
			}
			set
			{
				this._Bar11 = value;
			}
		}
		public System.Nullable<Avro.AvroDecimal> Bar12
		{
			get
			{
				return this._Bar12;
			}
			set
			{
				this._Bar12 = value;
			}
		}
		public Avro.AvroDecimal Bar13
		{
			get
			{
				return this._Bar13;
			}
			set
			{
				this._Bar13 = value;
			}
		}
		public System.Nullable<System.Int32> Bar14
		{
			get
			{
				return this._Bar14;
			}
			set
			{
				this._Bar14 = value;
			}
		}
		public Test.Bar15 Bar15
		{
			get
			{
				return this._Bar15;
			}
			set
			{
				this._Bar15 = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Bar6;
			case 2: return this.Bar7;
			case 3: return this.Bar8;
			case 4: return this.Bar9;
			case 5: return this.Bar10;
			case 6: return this.Bar11;
			case 7: return this.Bar12;
			case 8: return this.Bar13;
			case 9: return this.Bar14;
			case 10: return this.Bar15;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Bar6 = (Test.Bar6)fieldValue; break;
			case 2: this.Bar7 = (System.String)fieldValue; break;
			case 3: this.Bar8 = (System.String)fieldValue; break;
			case 4: this.Bar9 = (System.DateTime)fieldValue; break;
			case 5: this.Bar10 = (System.Nullable<Avro.AvroDecimal>)fieldValue; break;
			case 6: this.Bar11 = (System.Nullable<Avro.AvroDecimal>)fieldValue; break;
			case 7: this.Bar12 = (System.Nullable<Avro.AvroDecimal>)fieldValue; break;
			case 8: this.Bar13 = (Avro.AvroDecimal)fieldValue; break;
			case 9: this.Bar14 = (System.Nullable<System.Int32>)fieldValue; break;
			case 10: this.Bar15 = (Test.Bar15)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
